---------------------- MODULE ModuleName ---------------------
(* Imports and variable declarations*)
EXTENDS Naturals, Sequences, Integers, FiniteSets
--------------------------------------------------------------
(* Initial Conditions *)
Init == ...
TypeOK == ...
--------------------------------------------------------------
(* Body of the spec *)
Next == ...
Invariant == ...
--------------------------------------------------------------
(* Invariant declaration with temporal formula *)
THEOREM  Spec => ...
==============================================================
